build(*): update the module to rollup
ovh-ux/ng-ovh-chatbot pull request #7
Opened 2019-01-22 16:39 UTC by euhmeuh

Enjoy.

2019-01-22 20:38 UTC, FredericEspiau commented
Could you please be a bit more thorough @euhmeuh  ? What did you actually do, the commits and description of you PR are terse to say the least :)

2019-01-24 07:51 UTC, antleblanc requested changes
Well done.

I just add some comments regarding that some content has been copy/pasted and could be refactored I guess.

2019-01-24 07:51 UTC, antleblanc commented on rollup.config.js
> +        '@ovh-ux/translate-async-loader': 'translate-async-loader',
Could you please cleanup these globals?

2019-01-24 07:51 UTC, antleblanc commented on src/controller.js
> +  constructor(
```suggestion
  /* @ngInject */
  constructor(
```

2019-01-24 07:51 UTC, antleblanc commented on src/index.js
> +  .controller('chatbotController', ChatbotCtrl)
```suggestion
  .controller('ChatbotController', ChatbotCtrl)
```

2019-01-24 07:51 UTC, antleblanc commented on src/service.js
> +    this.$get = ['$http', '$q', ($http, $q) => {
```suggestion
    this.$get = /* @ngInject */ ($http, $q) => {
```

2019-01-24 07:51 UTC, antleblanc commented on src/service.js
> +const fakeChatbotData = [
Shouldn't be removed?

2019-01-24 07:51 UTC, antleblanc commented on src/index.js
> +  .constant('CHATBOT_MESSAGE_TYPES', {
Both `CHATBOT_MESSAGE_TYPES` and `CHATBOT_NGEMBED_OPTIONS` could be extracted to a `constants.js` file.

2019-01-24 07:51 UTC, antleblanc commented on src/directive.js
> +  controller: 'chatbotController',
```suggestion
  controller: 'ChatbotController',
```

2019-01-24 07:51 UTC, antleblanc commented on src/directive.js
> +  controllerAs: 'ctrl',
```suggestion
  controllerAs: '$ctrl',
```

2019-01-24 07:51 UTC, antleblanc commented on package.json
> +    "ovh-angular-user-pref": "^0.3.1"
Could you try the latest prerelease of `ng-ovh-user-pref` instead? 

```sh
yarn remove ovh-angular-user-pref 
yarn add --peer @ovh-ux/ng-ovh-user-pref
```

ref: https://github.com/ovh-ux/ng-ovh-user-pref/tree/v1.0.0-beta.0

Thanks:)

2019-01-24 08:06 UTC, antleblanc commented
/cc @jleveugle @cbourgois @frenautvh

2019-01-25 10:30 UTC, marie-j commented on src/index.less
> +@import (optional, reference) "../node_modules/ovh-ui-kit/packages/oui-color/_variables";
Would it make sense to use `~` to import instead ?

2019-01-31 16:12 UTC, euhmeuh commented
Comments fixed in https://github.com/ovh-ux/ng-ovh-chatbot/pull/8. Closing.

2019-01-31 16:12 UTC, closed without merging